{
  "openapi": "3.0.0",
  "info": {
    "title": "Magacare",
    "description": "API para controle de lista de desejos de ecommerce.",
    "termsOfService": "www.google.com.br",
    "contacts": {
      "email": "email@email.com"
    },
    "version": "1.0.0"
  },
  "servers": [{
    "url": "https://localhost:3000/api/health/ping",
    "description": "API teste"
  }],
  "tags": [
    {
      "name": "Clients",
      "description": "Rotas do módulo clients."
    }
  ],
  "paths": {
    "/clients": {
      "post": {
        "tags": [
          "Clients"
        ],
        "summary": "Create new client",
        "description": "Rote responsable to create new clients.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Cadastro de cliente"
              },
              "example": {
                "Clients": {
                  "value": {
                    "fullname": "Malu Campos",
                    "email": "marialuisa@email.com.br",
                    "birthdate": "16/01/2001",
                    "cpf": "12345678901",
                    "phonenumber": "81998929985",
                    "postalcode": "50070123",
                    "gender": "Mulher Cis",
                    "password": "testeteste123"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Client created."
          },
          "400": {
            "description": "The email or the CPF is already in use."
          },
          "500": {
            "description": "Error."
          }
        }
      }
    },
    "/clients/{id}": {
      "put": {
        "tags": [
          "Clients"
        ],
        "summary": "Update client",
        "description": "Rote that updates clients and it is not possible to update with an Email or with an CPF that already exists.",
        "parameters": [{
          "in": "path",
          "name": "id",
          "type": "string",
          "required": "true",
          "description": "Client's id to update."
        }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Update client"
              },
              "example": {
                "Clients": {
                  "value": {
                    "fullname": "Maria Luisa Campos",
                    "email": "marialuisa@email.com.br",
                    "birthdate": "16/01/2001",
                    "cpf": "12345678901",
                    "phonenumber": "81998929985",
                    "postalcode": "50070123",
                    "gender": "Mulher Cis",
                    "oldPassword": "teste123",
                    "password": "testeteste123",
                    "confirmPassword": "testeteste123"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Client updated."
          },
          "400": {
            "description": "The email or the CPF is already in use."
          },
          "401": {
            "description": "Some information is wrong."
          },
          "404": {
            "description": "Error."
          }
        }
      },
      "delete": {
        "tags": ["Clients"],
        "summary": "Delete clients by ID.",
        "description": "Rote responsable to delete clients. If the client has a wishlist, it's also deleted.",
        "parameters": [{
          "in": "path",
          "name": "id",
          "type": "string",
          "required": "true",
          "description": "Client's id to delete."
        }],
        "responses": {
          "200": {
            "description": "Client deleted."
          },
          "404": {
            "description": "Error."
          }
        }
      }
    },
    "clients/wishlists/{id}": {
      "get": {
        "tags": [
          "Clients"
        ],
        "summary": "Search client's wishlists.",
        "description": "Rote responsable to search the wishlist of the client by his id.",
        "parameters": [{
          "in": "path",
          "name": "id",
          "type": "string",
          "required": "true",
          "description": "Client's id to search wishlists"
        }],
        "responses": {
          "200": {
            "description": "OK."
          },
          "404": {
            "description": "Error."
          }
        }
      }
    },
    "clients/id/{id}": {
      "get": {
        "tags": [
          "Clients"
        ],
        "summary": "Search client by ID.",
        "description": "Rote responsable to search client with his ID.",
        "responses": {
          "200": {
            "description": "OK.",
            "schema": {
              "$ref":"#/components/schemas/Create client",
              "example": {
                "Clients": {
                  "value": {
                    "fullname": "Maria Luisa Campos",
                    "email": "marialuisa@email.com.br",
                    "birthdate": "16/01/2001",
                    "cpf": "12345678901",
                    "phonenumber": "81998929985",
                    "postalcode": "50070123",
                    "gender": "Mulher Cis",
                    "password": "testeteste123"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Error."
          }
        }
      }
    },
    "clients/email": {
      "get": {
        "tags": ["Clients"],
        "summary": "Search clients by email",
        "description": "Rote that search clients by his email by query params.",
        "parameters": [{
          "in": "query",
          "name": "email",
          "type": "string",
          "required": "true",
          "description": "Client's email to get his informations. "
        }]
      }
    },
    "clients/search": {
      "get": {
        "tags": [
          "Clients"
        ],
        "summary": "Search client with filter and pagination.",
        "description": "Rote responsable to search client by filter (name, id or gender) and pagination, where you can choose the page and the limit of clients in each page.",
        "parameters": [
          {
            "in": "query",
            "name": "searchBy",
            "type": "string",
            "required": "true",
            "description": "Decides the type of filter you want to use. It can be the client's id, name or gender."
          },
          {
            "in": "query",
            "name": "filter",
            "type": "string",
            "required": "true",
            "description": "Filter used to search the client."
          },
          {
            "in": "query",
            "name": "page",
            "type": "integer",
            "required": "false",
            "description": "Search's page. The default page is 1."
          },
          {
            "in": "query",
            "name": "limit",
            "type": "integer",
            "required": "false",
            "description": "How many clients showing in each page. The default quantity is 5."
          }
        ],
        "responses": {
          "200": {
            "description": "OK."
          },
          "404": {
            "description": "Error."
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Create client": {
        "type": "object",
        "properties": {
          "fullname": {
            "type": "string",
            "required": "true"
          },
          "email": {
            "type": "string",
            "required": "true",
            "lowercase": "true",
            "unique": "true"
          },
          "birthdate": {
            "type": "date",
            "required": "true"
          },
          "cpf": {
            "type": "string",
            "required": "true",
            "unique": "true"
          },
          "phonenumber": {
            "type": "string",
            "required": "true"
          },
          "postalcode": {
            "type": "string",
            "required": "true"
          },
          "gender": {
            "type": "string",
            "default": "prefiro não responder",
            "required": "true"
          },
          "password": {
            "type": "string",
            "required": "true"
          }
        }
      },
      "Update client": {
        "type": "object",
        "properties": {
          "fullname": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "lowercase": "true"
          },
          "birthdate": {
            "type": "date"
          },
          "cpf": {
            "type": "string"
          },
          "phonenumber": {
            "type": "string"
          },
          "postalcode": {
            "type": "string"
          },
          "gender": {
            "type": "string"
          },
          "oldPassword": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "confirmPassword": {
            "type": "string"
          }
        }
      }
    }
  }
}